# Generated by Django 5.1.5 on 2025-01-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_category_store_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
