# Generated by Django 5.1.5 on 2025-01-24 07:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_tag_alter_food_image_alter_food_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
